name: Build Windows App

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      
      - name: Build CLI + Web UI
        working-directory: cmd/smirnovtorrent
        run: go build -o smirnovtorrent.exe
      
      - name: Upload App
        uses: actions/upload-artifact@v4
        with:
          name: SmirnovTorrent
          path: cmd/smirnovtorrent/smirnovtorrent.exe
